### ISSUE TITLE
Datastore disk placement issue in v47 

### ISSUE THREAD

**Issue by brunograz** [cloudfoundry-incubator/bosh-vsphere-cpi-release#108] opened 2018-05-31 12:44 UTC
Hi,

We deployed a bosh director specifying the parameters listed at https://bosh.io/docs/init-vsphere/. What we noticed though was a strange behavior when deploying VMs. 
Every single ephemeral disk would use the same datastore until it fills up and return us the error `Error: Unknown CPI error 'Unknown' with message 'Module 'MonitorLoop' power on failed. ' in 'create_vm' CPI method`.

Following the documentation, we tried multiple configurations. From changing the regex in the init command to specifying the datastores/ds_cluster for persistent and ephemeral disks in the cloud config as per https://bosh.io/docs/vsphere-cpi/#resource-pools. None of those options worked and we were seeing the same behavior all the time.

Our final 'regex' looked like: `^(DS0|DS1|DS2|DS3|DS4|DS5|DS6)$` and even then only a single datastore was picked every time. 

The storage config comprises of a **single** datastore cluster with 6 datastores in it, SDRS is enabled. 
Every physical host has the permission to access the 6 datastores.

Interestingly, changing the cpi version from v47 to v45.1.0 and using the same regex as shown above resulted in the expected disk placement as for https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/blob/master/src/vsphere_cpi/lib/cloud/vsphere/datastore_picker.rb#L14. 

v47 has added support for SDRS and I wonder if that has impact on what was described above - is there an additional configuration required?. 

We didn't check if the same applies for v48 or v49.

**Comment by nehagjain15** [comment] 2018-05-31 19:40
@brunograz In in your config did you only specify the Datastore cluster which had those 6 datastores?
Could you share what was in your init command and in cloud config please.  
If you have the logs that would be of great help, if you could share those, so that we can see what cpi did. You can get cpi specific log from the deploy task using --cpi flag. If not do you mind retrying with v47 and then sharing the logs as that would help narrow down the bug quickly. v47 has SDRS support but it should not affect your config if you don't specify clusters in it. If you want to use SDRS support you can specify your datastores in cloud config as datastores: [{clusters: [datastrore_cluster_name1: {}  , datastore_cluster_name2: {}]}]

**Comment by nehagjain15** [comment] 2018-06-01 17:48
@brunograz we did find what the issue is and will be fixing it. Tracker [link](https://www.pivotaltracker.com/story/show/158039615)
If you do want to use v47 you can set 1 datastore in your global config and specify the datastore cluster in cloud_config. This should solve your problem until we push the fix

**Comment by yeshwantbabar** [comment] 2018-06-27 00:58
This issue is fixed in V50.

**Closed by yeshwantbabar** 2018-06-27 00:58 UTC
